### ISSUE TITLE
Take composer version aliases into account when setting plugin version

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/plugin-installer#8]
Take composer version aliases into account when setting plugin version. This will fix many issues that I have when requiring forks that have a `dev-x` version in composer. Example:

`"craftcms/commerce": "dev-bugfix/payment-currency-convert as 3.3.4.1",` saves `dev-bugfix/payment-currency-convert` as the plugins' version. In commerce itself, there is a lot of `version_compare` going on which doesn't play nice with this logic.

So there is really no way for me now to load a commerce fork...

**Comment by brandonkelly** [comment]
Not possible, unfortunately (see https://github.com/composer/composer/issues/9467).
